[package]
name = "poters"
version = "0.1.0"
authors = ["mthh <matthieu.viry@cnrs.fr>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
error-chain = "0.10"
csv = "0.15"
clap = "2.23"
scan-rules = "0.2.0"
geojson = "0.8"

[[bin]]
name = "poters"
doc = false
